name: PR Validation

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  validate:
    name: Validate on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        llvm-version: ['21']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install LLVM
      uses: KyleMayes/install-llvm-action@v2.0.8
      with:
        version: ${{ matrix.llvm-version }}
        directory: ${{ runner.temp }}/llvm

    - name: Set LLVM environment variables
      run: |
        echo "LLVM_LIB_DIR=${{ runner.temp }}/llvm/lib" >> $GITHUB_ENV

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Run Biome check (linting, formatting, and type checking)
      run: bunx biome ci

    - name: Run TypeScript type check
      run: bunx tsc --noEmit

    - name: Run dummy FFI tests
      run: bun test/dummy.ts

    - name: Run tests
      run: bun test
