name: PR Validation

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  validate:
    name: Validate on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        llvm-version: ['21']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install LLVM (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        # Install LLVM 21 using official LLVM installation script
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 21
        # Alternative apt installation (commented out as LLVM 21 not available in standard repos)
        # sudo apt update
        # sudo apt install -y llvm-21 llvm-21-dev libllvm21

    - name: Install LLVM (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install llvm@21

    - name: Set LLVM environment variables (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        echo "LLVM_LIB_DIR=/usr/lib/llvm-21/lib" >> $GITHUB_ENV

    - name: Set LLVM environment variables (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        echo "LLVM_LIB_DIR=$(brew --prefix llvm@21)/lib" >> $GITHUB_ENV

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Run Biome check (linting, formatting, and type checking)
      run: bunx biome ci

    - name: Run TypeScript type check
      run: bunx tsc --noEmit

    - name: Run tests
      run: bun test
